client/urls.py
"""urls for client application."""

from django.urls import path

from client.client_apis import client_detail_view_api, client_view
from client.views.client_views import (
    client_add_view,
    client_delete_view,
    client_detail_view,
    client_list_view,
    client_update_view
)
from client.views.measurement_views import measurements_add_view, measurements_update_view
from .views.client_views import client_dashboard
app_name = 'client'

urlpatterns = [
    path('clients/', client_list_view, name='clients'),
    path('clients/detail/<int:pk>/', client_detail_view, name='client_detail'),
    path('clients/delete/', client_delete_view, name='client_delete'),
    path('clients/add/', client_add_view, name='client_add'),
    path('clients/update/<int:pk>/', client_update_view, name='client_update'),
    path('clients/measurements/add/<int:client_id>/', measurements_add_view, name='measurment_add'),
    path('clients/measurements/update/<int:client_id>/', measurements_update_view, name='measurment_update'),
    path('dashboard/', client_dashboard, name='client_dashboard'),
    # path('create-client/', ClientCreateView.as_view(), name='create_client'),
    # API END POINTS
    path('clients/api/', client_view, name='clients_api'),
    path('clients/api/detail/<int:pk>/', client_detail_view_api, name='client_detail_api'),
    path('clients/api/delete/<int:pk>/', client_detail_view_api, name='client_delete_api'),
    path('clients/api/add/', client_view, name='client_add_api'),
    path('clients/api/update/<int:pk>/', client_detail_view_api, name='client_update_api'),
]

help/urls.py
from django.urls import path
from .views import HelpListView, HelpDetailView, HelpSearchView, submit_feedback

app_name = 'help'

urlpatterns = [
    path('', HelpListView.as_view(), name='help_index'),  # Ensure this name matches the one used in your templates
    path('<int:pk>/', HelpDetailView.as_view(), name='help_detail'),
    path('search/', HelpSearchView.as_view(), name='help_search'),
    path('feedback/', submit_feedback, name='help_feedback'),
]

order/urls.py
"""urls for order application."""

from django.urls import path

from order.views.order_views import order_add_view, order_detail_view, order_list_view, order_update_view,orders_with_pending_payments,header_top_view
from order.views.task_views import task_add_view, task_delete_view, task_detail_view, task_list_view, task_update_view

app_name = 'order'

urlpatterns = [
    path('orders/', order_list_view, name='orders'),
    path('order/<int:id>/', order_detail_view, name='order_detail'),
    path('order/add/<int:client_id>/', order_add_view, name='order_add'),
    path('order/update/<int:id>/', order_update_view, name='order_update'),
    path('orders/pending/', orders_with_pending_payments, name='pending_orders'),
    path('header/', header_top_view, name='header_top'),
    # TASK URLS
    path('tasks/', task_list_view, name='tasks'),
    path('task/<int:id>/', task_detail_view, name='task_detail'),
    path('task/add/<int:order_id>/', task_add_view, name='task_add'),
    path('task/update/<int:id>/', task_update_view, name='task_update'),
    path('task/delete/', task_delete_view, name='task_delete'),
]

product/urls.py
"""urls for product application."""

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from product.views.product_images_views import product_images_add_view, product_images_update_view
from product.views.product_views import (
    product_add_view,
    product_delete_view,
    product_detail_view,
    product_list_view,
    product_update_view
)

app_name = 'product'

urlpatterns = [
    path('products/', product_list_view, name='products'),
    path('product/<int:id>/', product_detail_view, name='product_detail'),
    path('product/add/', product_add_view, name='product_add'),
    path('product/update/<int:id>/', product_update_view, name='product_update'),
    path('product/delete/', product_delete_view, name='product_delete'),

    path('product_images/add/<int:product_id>/', product_images_add_view, name='product_images_add'),
    path('product_images/update/<int:product_id>/', product_images_update_view, name='product_images_update'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tms/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('tailor_management_system.urls')),
    path('', include('client.urls')),
    path('', include('order.urls')),
    path('', include('employee.urls')),
    path('', include('product.urls')),
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
    path('', include('notifications.urls')),
    path('help/', include('help.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # Provides login, logout, etc.
]

templates/header/dashboard-head-dropdown.html
{% load static %}
<div class="kt-header__brand-nav">
    <div class="dropdown">
        <button type="button" class="btn btn-pill btn-default dropdown-toggle" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="true">
            Dashboard
        </button>
        <div class="dropdown-menu dropdown-menu-fit dropdown-menu-md">
            <ul class="kt-nav kt-nav--bold kt-nav--md-space kt-margin-t-20 kt-margin-b-20">
                <li class="kt-nav__item">
                    <a class="kt-nav__link active" href="#">
                        <span class="kt-nav__link-icon"><i class="flaticon2-user"></i></span>
                        <span class="kt-nav__link-text">Human Resources</span>
                    </a>
                </li>
                <li class="kt-nav__item">
                    <a class="kt-nav__link" href="#">
                        <span class="kt-nav__link-icon"><i class="flaticon-feed"></i></span>
                        <span class="kt-nav__link-text">Customer Relationship</span>
                    </a>
                </li>
                <li class="kt-nav__item">
                    <a class="kt-nav__link" href="#">
                        <span class="kt-nav__link-icon"><i class="flaticon2-settings"></i></span>
                        <span class="kt-nav__link-text">Order Processing</span>
                    </a>
                </li>
                <li class="kt-nav__item">
                    <a class="kt-nav__link" href="#">
                        <span class="kt-nav__link-icon"><i class="flaticon2-chart2"></i></span>
                        <span class="kt-nav__link-text">Accounting</span>
                    </a>
                </li>
                <li class="kt-nav__separator"></li>
                <li class="kt-nav__item">
                    <a class="kt-nav__link" href="#">
                        <span class="kt-nav__link-icon"><i class="flaticon-security"></i></span>
                        <span class="kt-nav__link-text">Finance</span>
                    </a>
                </li>
                <li class="kt-nav__item">
                    <a class="kt-nav__link" href="#">
                        <span class="kt-nav__link-icon"><i class="flaticon2-cup"></i></span>
                        <span class="kt-nav__link-text">Administration</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

templates/header/head.html
{% load static %}
{% load clean_title %}
<!DOCTYPE html>

<html lang="en">

<head>
    <base href="../">
    <meta charset="utf-8" />
    <title>TMS | {% clean_title title %}</title>
    <meta name="description" content="Latest updates and statistic charts">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <!--begin::Fonts -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Asap+Condensed:500">

    <!--end::Fonts -->
    		<!--begin::Page Custom Styles(used by this page) -->
    <link href="{% static 'css/pages/wizard/wizard-2.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/pages/inbox/inbox.css' %}" rel="stylesheet" type="text/css" />
    <!--begin::Page Vendors Styles(used by this page) -->
    <link href="{% static 'plugins/custom/fullcalendar/fullcalendar.bundle.css' %}" rel="stylesheet" type="text/css" />

    <!--end::Page Vendors Styles -->

    <!--begin::Global Theme Styles(used by all pages) -->
    <link href="{% static 'plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/style.bundle.css' %}" rel="stylesheet" type="text/css" />

    <!--end::Global Theme Styles -->

    <!--begin::Layout Skins(used by all pages) -->

    <!--end::Layout Skins -->
    <link rel="shortcut icon" href="{% static 'media/logos/favicon.ico' %}" />


</head>

templates/header/header-menu.html
{% load static %}
{% load get_page_group %}
{% get_page_group title as group %}

<!-- begin: Header Menu -->
<button class="kt-header-menu-wrapper-close" id="kt_header_menu_mobile_close_btn"><i class="la la-close"></i></button>
<div class="kt-header-menu-wrapper" id="kt_header_menu_wrapper">
    <div id="kt_header_menu" class="kt-header-menu kt-header-menu-mobile ">
        <ul class="kt-menu__nav ">
            <li class="kt-menu__item  kt-menu__item--open {% if group == "DASHBOARD" %}kt-menu__item--here{% endif %} kt-menu__item--submenu kt-menu__item--rel kt-menu__item--open"
                data-ktmenu-submenu-toggle="hover" aria-haspopup="true"><a
                    href="{% url 'tailor_management_system:dashboard' %}" class="kt-menu__link"><span
                        class="kt-menu__link-text">Dashboard</span><i
                        class="kt-menu__ver-arrow la la-angle-right"></i></a>
            </li>
            <li class="kt-menu__item  {% if group == "CLIENT" %}kt-menu__item--here{% endif %} kt-menu__item--submenu kt-menu__item--rel"
                data-ktmenu-submenu-toggle="click" aria-haspopup="true"><a href="javascript:;"
                    class="kt-menu__link kt-menu__toggle"><span class="kt-menu__link-text">Clients</span><i
                        class="kt-menu__ver-arrow la la-angle-right"></i></a>
                <div class="kt-menu__submenu kt-menu__submenu--classic kt-menu__submenu--left">
                    <ul class="kt-menu__subnav">
                        <li class="kt-menu__item  kt-menu__item--submenu" data-ktmenu-submenu-toggle="hover"
                            aria-haspopup="true"><a href="{% url 'client:clients' %}" class="kt-menu__link"><i
                                    class="kt-menu__link-icon flaticon2-list-3"></i><span
                                    class="kt-menu__link-text">View Clients</span></a>
                        </li>
                        <li class="kt-menu__item  kt-menu__item--submenu" data-ktmenu-submenu-toggle="hover"
                            aria-haspopup="true"><a href="{% url 'client:client_add' %}" class="kt-menu__link"><i
                                    class="kt-menu__link-icon flaticon-plus"></i><span class="kt-menu__link-text">Add
                                    Client</span></i></a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="kt-menu__item {% if group == "PRODUCT" %}kt-menu__item--here{% endif %} kt-menu__item--submenu kt-menu__item--rel"
                data-ktmenu-submenu-toggle="click" aria-haspopup="true"><a href="javascript:;"
                    class="kt-menu__link kt-menu__toggle"><span class="kt-menu__link-text">Products</span><i
                        class="kt-menu__ver-arrow la la-angle-right"></i></a>
                <div class="kt-menu__submenu kt-menu__submenu--classic kt-menu__submenu--left">
                    <ul class="kt-menu__subnav">
                        <li class="kt-menu__item  kt-menu__item--submenu" data-ktmenu-submenu-toggle="hover"
                            aria-haspopup="true"><a href="{% url 'product:products' %}" class="kt-menu__link"><i
                                    class="kt-menu__link-icon flaticon2-list-3"></i><span
                                    class="kt-menu__link-text">View Products</span></a>
                        </li>
                        <li class="kt-menu__item  kt-menu__item--submenu" data-ktmenu-submenu-toggle="hover"
                            aria-haspopup="true"><a href="{% url 'product:product_add' %}" class="kt-menu__link"><i
                                    class="kt-menu__link-icon flaticon-plus"></i><span class="kt-menu__link-text">Add
                                    Products</span></a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="kt-menu__item {% if group == "EMPLOYEE" %}kt-menu__item--here{% endif %} kt-menu__item--submenu kt-menu__item--rel"
                data-ktmenu-submenu-toggle="click" aria-haspopup="true"><a href="javascript:;"
                    class="kt-menu__link kt-menu__toggle"><span class="kt-menu__link-text">Employees</span><i
                        class="kt-menu__ver-arrow la la-angle-right"></i></a>
                <div class="kt-menu__submenu kt-menu__submenu--classic kt-menu__submenu--left">
                    <ul class="kt-menu__subnav">
                        <li class="kt-menu__item  kt-menu__item--submenu" data-ktmenu-submenu-toggle="hover"
                            aria-haspopup="true"><a href="{% url 'employee:employees' %}" class="kt-menu__link"><i
                                    class="kt-menu__link-icon flaticon2-list-3"></i><span
                                    class="kt-menu__link-text">View Employee</span></a>
                        </li>
                        <li class="kt-menu__item  kt-menu__item--submenu" data-ktmenu-submenu-toggle="hover"
                            aria-haspopup="true"><a href="{% url 'employee:employee_add' %}" class="kt-menu__link"><i
                                    class="kt-menu__link-icon flaticon-plus"></i><span class="kt-menu__link-text">Add
                                    Employee</span></a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="kt-menu__item {% if group == "ORDER" %}kt-menu__item--here{% endif %} kt-menu__item--submenu kt-menu__item--rel"
                data-ktmenu-submenu-toggle="click" aria-haspopup="true"><a href="javascript:;"
                    class="kt-menu__link kt-menu__toggle"><span class="kt-menu__link-text">Orders</span><i
                        class="kt-menu__ver-arrow la la-angle-right"></i></a>
                <div class="kt-menu__submenu kt-menu__submenu--classic kt-menu__submenu--left">
                    <ul class="kt-menu__subnav">
                        <li class="kt-menu__item  kt-menu__item--submenu" data-ktmenu-submenu-toggle="hover"
                            aria-haspopup="true"><a href="{% url 'order:orders' %}" class="kt-menu__link"><i
                                    class="kt-menu__link-icon flaticon2-list-3"></i><span
                                    class="kt-menu__link-text">View Orders</span></a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="kt-menu__item {% if group == "TASK" %}kt-menu__item--here{% endif %} kt-menu__item--submenu kt-menu__item--rel"
                data-ktmenu-submenu-toggle="click" aria-haspopup="true"><a href="javascript:;"
                    class="kt-menu__link kt-menu__toggle"><span class="kt-menu__link-text">Tasks</span><i
                        class="kt-menu__ver-arrow la la-angle-right"></i></a>
                <div class="kt-menu__submenu kt-menu__submenu--classic kt-menu__submenu--left">
                    <ul class="kt-menu__subnav">
                        <li class="kt-menu__item  kt-menu__item--submenu" data-ktmenu-submenu-toggle="hover"
                            aria-haspopup="true"><a href="{% url 'order:tasks' %}" class="kt-menu__link"><i
                                    class="kt-menu__link-icon flaticon2-list-3"></i><span
                                    class="kt-menu__link-text">View Tasks</span></a>
                        </li>
                    </ul>
                </div>
            </li>
            <!-- Example of how to use the URL template tag -->
            <li class="kt-menu__item  kt-menu__item--open {% if group == "DASHBOARD" %}kt-menu__item--here{% endif %} kt-menu__item--submenu kt-menu__item--rel kt-menu__item--open"
                data-ktmenu-submenu-toggle="hover" aria-haspopup="true"><a
                href="{% url 'help:help_index' %}" class="kt-menu__link"><span
                        class="kt-menu__link-text">Help For Employee</span><i
                        class="kt-menu__ver-arrow la la-angle-right"></i></a>
            </li>
           

        </ul>
    </div>
</div>

<!-- end: Header Menu -->

templates/header/header-mobile.html
{% load static %}
<!-- begin:: Header Mobile -->
<div id="kt_header_mobile" class="kt-header-mobile  kt-header-mobile--fixed ">
    <div class="kt-header-mobile__logo">
        <a href="index.html">
            <img alt="Logo" src="{% static 'media/logos/logo-10-sm.png' %}" />
        </a>

    </div>
    <div class="kt-header-mobile__toolbar">
        <button class="kt-header-mobile__toolbar-toggler" id="kt_header_mobile_toggler"><span></span></button>
        <button class="kt-header-mobile__toolbar-topbar-toggler" id="kt_header_mobile_topbar_toggler"><i
                class="flaticon-more-1"></i></button>
    </div>
</div>

templates/header/header.html
{% load static %}
{% block header-mobile %}
{% include 'header/header-mobile.html' %}
{% endblock %}
<!-- begin:: Header -->
<div id="kt_header" class="kt-header kt-grid__item  kt-header--fixed " data-ktheader-minimize="on">
    <div class="kt-header__top">
        <div class="kt-container  kt-container--fluid ">

            <!-- begin:: Brand -->
            <div class="kt-header__brand   kt-grid__item" id="kt_header_brand">
                <div class="kt-header__brand-logo">
                    <a href="{% url 'tailor_management_system:dashboard' %}">
                        <img alt="Logo" src="{% static 'media/logos/logo-10.png' %}"
                            class="kt-header__brand-logo-default" />
                    </a>
                </div>
            </div>

            <!-- end:: Brand -->
            {% block header-topbar %}
            {% include 'header/header-topbar.html' %}
            {% endblock %}
        </div>
    </div>
    <div class="kt-header__bottom">
        <div class="kt-container ">

            <!-- begin: Header Menu -->
            <button class="kt-header-menu-wrapper-close" id="kt_header_menu_mobile_close_btn"><i
                    class="la la-close"></i></button>
            {% block header-menu %}
            {% include 'header/header-menu.html' %}
            {% endblock %}

            <!-- end: Header Menu -->
        </div>
    </div>
</div>

<!-- end:: Header -->