employee/urls.py
"""urls for employee application."""

from django.urls import path

from employee.views import (
    employee_add_view,
    employee_delete_view,
    employee_detail_view,
    employee_list_view,
    employee_update_view
)

app_name = 'employee'

urlpatterns = [
    path('employees/', employee_list_view, name='employees'),
    path('employee/<int:id>/', employee_detail_view, name='employee_detail'),
    path('employee/add/', employee_add_view, name='employee_add'),
    path('employee/update/<int:id>/', employee_update_view, name='employee_update'),
    path('employee/delete/', employee_delete_view, name='employee_delete'),
]

order/urls.py
"""urls for order application."""

from django.urls import path

from order.views.order_views import order_add_view, order_detail_view, order_list_view, order_update_view,orders_with_pending_payments,header_top_view
from order.views.task_views import task_add_view, task_delete_view, task_detail_view, task_list_view, task_update_view

app_name = 'order'

urlpatterns = [
    path('orders/', order_list_view, name='orders'),
    path('order/<int:id>/', order_detail_view, name='order_detail'),
    path('order/add/<int:client_id>/', order_add_view, name='order_add'),
    path('order/update/<int:id>/', order_update_view, name='order_update'),
    path('orders/pending/', orders_with_pending_payments, name='pending_orders'),
    path('header/', header_top_view, name='header_top'),
    # TASK URLS
    path('tasks/', task_list_view, name='tasks'),
    path('task/<int:id>/', task_detail_view, name='task_detail'),
    path('task/add/<int:order_id>/', task_add_view, name='task_add'),
    path('task/update/<int:id>/', task_update_view, name='task_update'),
    path('task/delete/', task_delete_view, name='task_delete'),
]

tms/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('tailor_management_system.urls')),
    path('', include('client.urls')),
    path('', include('order.urls')),
    path('', include('employee.urls')),
    path('', include('product.urls')),
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
    path('', include('notifications.urls')),
    path('help/', include('help.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # Provides login, logout, etc.
]

employee/models.py
"""Models for employee application."""

from django.db import models


class Employee(models.Model):
    """Employee model."""

    name = models.CharField(max_length=30)
    gender = models.CharField(
        max_length=2,
        choices=[('M', 'Male'), ('F', 'Female')],
        default='M'
    )
    address = models.TextField(max_length=500)
    phone_number = models.CharField(max_length=15, unique=True)
    joining_date = models.DateField(auto_now_add=True)

    objects = models.Manager()

    def __str__(self):
        """Convert object to String."""
        return 'name:{} - Phone:{} - JoiningDate:{}'.format(
            self.name,
            self.phone_number,
            self.joining_date
        )

employee/forms.py
"""Forms for employee application."""

import re

from django import forms
from django.core.exceptions import ValidationError

from employee.models import Employee


class EmployeeForm(forms.ModelForm):
    """Order model mapped form."""

    name = forms.CharField(max_length=30, min_length=4)
    address = forms.CharField(widget=forms.Textarea, max_length=500, min_length=10)
    phone_number = forms.CharField(max_length=15, min_length=6)

    class Meta:
        """Specifying fields to include."""

        model = Employee
        exclude = ('joining_date',)

    def clean_name(self):
        """Check if name is valid."""
        name = self.cleaned_data['name']

        if not self._validate_name(name):
            raise ValidationError('Invalid name.')

        return name

    def clean_phone_number(self):
        """Check if phone is valid."""
        phone_number = self.cleaned_data['phone_number']

        if not self._validate_phone_number(phone_number):
            raise ValidationError('Invalid phone number.')

        return phone_number

    def _validate_name(self, name):
        """Match valid name regex with name field."""
        return bool(re.match(
            r'^[_A-z]*((-|\s)*[_A-z])*$',
            str(name)
        ))

    def _validate_phone_number(self, phone):
        """Match valid phone number regex with phone field."""
        return bool(re.match(
            r'^[+]{1,1}[(]{0,1}[0-9]{1,4}[)]{0,1}[-\s\.0-9]{0,15}$',
            str(phone)
        ))

employee/views.py
"""Views for order application."""

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404, redirect, render
from rest_framework.views import View

from employee.forms import EmployeeForm
from employee.models import Employee
from order.models import Task


class EmployeeListView(LoginRequiredMixin, View):
    """List all employees."""

    def _get_employee_with_tasks(self, employees):
        """Get employees against number and status of tasks."""
        task_groupby_employee = Task.objects.all().values('employee').annotate(total=Count('employee'))
        employee_with_no_of_tasks = {}
        for employee in employees:
            tasks = Task.objects.filter(employee=employee)
            total_task_count = tasks.count()
            pending_task_count = tasks.exclude(status=Task.COMPLETED).count()
            percent_complete = 0
            if total_task_count > 0:
                percent_complete = round(((total_task_count - pending_task_count)/total_task_count) * 100, 2)
            completed_task_count = total_task_count - pending_task_count
            employee_with_no_of_tasks[employee.id] = (
                total_task_count,
                pending_task_count,
                percent_complete,
                completed_task_count
            )
        return employee_with_no_of_tasks

    def get(self, request):
        """Render employee list template.."""
        employees = Employee.objects.all().order_by('name')

        employee_with_no_of_tasks = self._get_employee_with_tasks(employees)

        context = {
            'employees': employees,
            'employee_with_no_of_tasks': employee_with_no_of_tasks
        }
        return render(request, 'employee/list-employees.html', context)

    def post(self, request):
        """Render employee list template.."""
        query = request.POST.get('search_query')
        employees = Employee.objects.all().order_by('name')

        if query:
            employees = employees.filter(
                Q(name__icontains=query)
                | Q(phone_number__icontains=query)
            )

        employee_with_no_of_tasks = self._get_employee_with_tasks(employees)

        context = {
            'employees': employees,
            'employee_with_no_of_tasks': employee_with_no_of_tasks,
            'query': query
        }
        return render(request, 'employee/list-employees.html', context)


employee_list_view = EmployeeListView.as_view()


class EmployeeDetailView(LoginRequiredMixin, View):
    """Class based view for Employee for detail of Employee."""

    def get(self, request, id):
        """Render Employee detail tempalte.."""
        employee = Employee.objects.get(id=id)
        context = {
            'employee': employee,
            'tasks': Task.objects.filter(employee=employee)
        }
        return render(request, 'employee/employee-detail.html', context)


employee_detail_view = EmployeeDetailView.as_view()


class EmployeeAddView(LoginRequiredMixin, View):
    """Class based view for adding new Employee."""

    def get(self, request):
        """Return add new Employee form."""
        form = EmployeeForm()
        return render(request, 'employee/add-employee.html',
                      {'form': form, 'func': 'Add'})

    def post(self, request):
        """Save employee and redirect to employee list."""
        form = EmployeeForm(request.POST)
        if form.is_valid():
            new_employee = form.save()
            return redirect('employee:employee_detail', id=new_employee.id)
        else:
            return render(request, 'employee/add-employee.html', {'form': form, 'func': 'Add'})


employee_add_view = EmployeeAddView.as_view()


class EmployeeUpdateView(LoginRequiredMixin, View):
    """Class based view for adding new Employee."""

    def get(self, request, id):
        """Return add new Employee form."""
        employee = get_object_or_404(Employee, id=id)
        form = EmployeeForm(instance=employee)
        return render(request, 'employee/add-employee.html',
                      {'form': form, 'func': 'Update', 'employee': employee})

    def post(self, request, id):
        """Save employee and redirect to employee list."""
        employee = get_object_or_404(Employee, id=id)
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            new_employee = form.save()
            return redirect('employee:employee_detail', id=new_employee.id)
        else:
            return render(request, 'employee/add-employee.html', {'form': form, 'func': 'Update', 'employee': employee})


employee_update_view = EmployeeUpdateView.as_view()


class EmployeeDeleteView(LoginRequiredMixin, View):
    """Class based view for deleting Employee."""

    def post(self, request):
        """Delete employee."""
        id = request.POST.get('id')
        employee = get_object_or_404(Employee, id=id)
        employee.delete()
        return redirect('employee:employees')


employee_delete_view = EmployeeDeleteView.as_view()

employee/templates/employee/add-employee.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}
{% block content %}
<!-- begin:: Content -->
<div class="kt-container  kt-grid__item kt-grid__item--fluid">

    <!--begin::Portlet-->
    <div class="kt-portlet">
        <div class="kt-portlet__head">
            <div class="kt-portlet__head-label">
                <h3 class="kt-portlet__head-title">
                    Add Details
                </h3>
            </div>
        </div>

        <!--begin::Form-->
        {% if func == "Add" %}
        <form class="kt-form kt-portlet__body" action="{% url 'employee:employee_add' %}" method="post">
        {% else %}
        <form class="kt-form kt-portlet__body" action="{% url 'employee:employee_update' employee.id %}" method="post">
        {% endif %}    
            {% csrf_token %}
            {{ form|crispy }}
            <div class="kt-portlet__foot">
                <div class="kt-form__actions">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-secondary">Reset</button>
                </div>
            </div>
        </form>

        <!--end::Form-->
    </div>

    <!--end::Portlet-->
</div>

<!-- end:: Content -->
{% endblock %}

employee/templates/employee/employee-detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load get_status %}
{% load static %}
{% block content %}
<!-- begin:: Content -->
<div class="kt-container  kt-grid__item kt-grid__item--fluid">
    <!--Begin::App-->
    <div class="kt-grid kt-grid--desktop kt-grid--ver kt-grid--ver-desktop kt-app">

        <!--Begin:: App Aside Mobile Toggle-->
        <button class="kt-app__aside-close" id="kt_user_profile_aside_close">
            <i class="la la-close"></i>
        </button>

        <!--End:: App Aside Mobile Toggle-->

        <!--Begin:: App Aside-->
        <div class="kt-grid__item kt-app__toggle kt-app__aside" id="kt_user_profile_aside">

            <!--Begin::Portlet-->
            <div class="kt-portlet kt-portlet--height-fluid-">
                <div class="kt-portlet__head kt-portlet__head--noborder">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                        </h3>
                    </div>
                    <div class="kt-portlet__head-toolbar">
                        <a href="#" class="btn btn-clean btn-sm btn-icon btn-icon-md" data-toggle="dropdown">
                            <i class="flaticon-more-1"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <ul class="kt-nav">
                                <li class="kt-nav__item">
                                    <a href="{% url 'employee:employee_update' employee.id %}" class="kt-nav__link">
                                        <i class="kt-nav__link-icon flaticon2-pen"></i>
                                        <span class="kt-nav__link-text">Edit</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="kt-portlet__body">

                    <!--begin::Widget -->
                    <div class="kt-widget kt-widget--user-profile-2">
                        <div class="kt-widget__head">
                            <div class="kt-widget__info" style="padding-left: 0em !important;">
                                <a class="kt-widget__username">
                                    {{ employee.name }}
                                </a>
                            </div>
                        </div>
                        </br>
                        <div class="kt-widget__body">
                            <div class="kt-widget__item">
                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">Name:</span>
                                    <a class="kt-widget__data">{{ employee.name }}</a>
                                </div>
                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">Phone:</span>
                                    <a class="kt-widget__data">{{ employee.phone_number }}</a>
                                </div>
                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">Gender:</span>
                                    <a class="kt-widget__data">{{ employee.gender }}</a>
                                </div>
                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">Joining Date:</span>
                                    <a class="kt-widget__data">{{ employee.joining_date }}</a>
                                </div>
                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">Address:</span>
                                    <span class="kt-widget__data">{{ employee.address }}</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!--end::Widget -->

                </div>
            </div>

            <!--End::Portlet-->

        </div>

        <!--End:: App Aside-->

        <!--Begin:: App Content-->
        <div class="kt-grid__item kt-grid__item--fluid kt-app__content">
            <div class="row">
                <div class="col-xl-12">

                    <!--begin:: Widgets/Finance Summary-->
                    <div class="kt-portlet kt-portlet--height-fluid">
                        <div class="kt-portlet__head">
                            <div class="kt-portlet__head-label">
                                <h3 class="kt-portlet__head-title">
                                    Tasks
                                </h3>
                            </div>
                        </div>
                        {% if tasks %}
                        {% for task in tasks %}
                        <div class="kt-portlet__body">
                            <div class="kt-widget12">
                                <div class="kt-portlet__head-toolbar" style="margin-left: 90% !important;">
                                    <a href="#" class="btn btn-label-brand btn-sm  btn-bold dropdown-toggle"
                                        data-toggle="dropdown">
                                        More
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-fit dropdown-menu-md">

                                        <!--begin::Nav-->
                                        <ul class="kt-nav">
                                            <li class="kt-nav__head">
                                                Task Options
                                            </li>
                                            <li class="kt-nav__separator"></li>
                                            <li class="kt-nav__item">
                                                <a href="{% url 'order:task_detail' task.id %}" class="kt-nav__link">
                                                    <i class="kt-nav__link-icon flaticon2-expand"></i>
                                                    <span class="kt-nav__link-text">Details</span>
                                                </a>
                                            </li>
                                            <li class="kt-nav__item">
                                                <a href="{% url 'order:task_update' task.id %}" class="kt-nav__link">
                                                    <i class="kt-nav__link-icon flaticon2-pen"></i>
                                                    <span class="kt-nav__link-text">Update</span>
                                                </a>
                                            </li>
                                        </ul>

                                        <!--end::Nav-->
                                    </div>
                                </div>
                                <div class="kt-widget12__content">
                                    <div class="kt-widget12__item">
                                        <div class="kt-widget12__info">
                                            <span class="kt-widget12__desc">Order#</span>
                                            <a href="{% url 'order:order_detail' task.order.id %}"><span
                                                    class="kt-widget12__value">{{ task.order.id }}</span></a>
                                        </div>
                                        <div class="kt-widget12__info">
                                            <span class="kt-widget12__desc">Task Status</span>
                                            <span class="kt-widget12__value">{% get_status "TASK" task.status %}</span>
                                        </div>
                                    </div>
                                    <div class="kt-widget12__item">
                                        <div class="kt-widget12__info">
                                            <span class="kt-widget12__desc">Task#</span>
                                            <a href="{% url 'order:task_detail' task.id %}"><span
                                                    class="kt-widget12__value">{{ task.id }}</span></a>
                                        </div>
                                        <div class="kt-widget12__info">
                                            <span class="kt-widget12__desc">Deadline</span>
                                            <span class="kt-widget12__value">{{ task.deadline }}</span>
                                        </div>
                                    </div>
                                    <div class="kt-widget12__item">
                                        <div class="kt-widget12__info">
                                            <span class="kt-widget12__desc">Description</span>
                                            <span class="kt-widget12__value">{{ task.description }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        {% else %}
                        <p class="h5 text-primary text-center" style="margin-right: 46% !important;">You haven't
                            assigned any tasks to this employee yet.</p>
                        {% endif %}
                    </div>

                    <!--end:: Widgets/Finance Summary-->
                </div>
            </div>
        </div>


        <!--End:: App Content-->
    </div>
</div>
<!-- end:: Content -->
{% endblock %}

employee/templates/employee/employee-info.html
<div class="row text-center mt-3">
    <div class="col-sm-12">
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <td align="right">
                        <p><b>Name: </b></p>
                    </td>
                    <td align=left>
                        <p>{{ employee.name }}</p>
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        <p><b>Phone: </b></p>
                    </td>
                    <td align=left>
                        <p>{{ employee.phone_number }}</p>
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        <p><b>Gender: </b></p>
                    </td>
                    <td align=left>
                        <p>{{ employee.gender }}</p>
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        <p><b>Joining Date: </b></p>
                    </td>
                    <td align=left>
                        <p>{{ employee.joining_date }}</p>
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        <p><b>Address: </b></p>
                    </td>
                    <td align=left>
                        <p>{{ employee.address }}</p>
                    </td>
                </tr>
            </tbody>
        </table>
        <a href="{% url 'employee:employee_update' employee.id %}" class="text-center btn-outline-primary"> <Button
                class="btn btn-primary">Update</Button></a>
    </div>
</div>

employee/templates/employee/list-employees.html
{% extends 'base.html' %}
{% load static %}
{% load clean_title %}
{% load get_dict_value %}
{% block content %}
<!-- begin:: Content -->
{% for employee in employees %}
<div class="kt-container  kt-grid__item kt-grid__item--fluid">

    {% get_dict_value employee_with_no_of_tasks employee.id as task_tuple %}
    <!--begin:: Portlet-->
    <div class="kt-portlet">
        <div class="kt-portlet__body">
            <div class="kt-widget kt-widget--user-profile-3">
                <div class="kt-widget__top">
                    <div class="kt-widget__content">
                        <div class="kt-widget__head">
                            <a href="{% url 'employee:employee_detail' employee.id %}" class="kt-widget__username">
                                {{ employee.name }}
                            </a>
                            <div class="kt-widget__action">
                                <a href="{% url 'employee:employee_detail' employee.id %}"
                                    class="btn btn-label-success btn-sm btn-upper">Employee Details</a>&nbsp;
                            </div>
                        </div>
                        <div class="kt-widget__subhead">
                            <a><i class="flaticon2-calendar-3"></i>{{ employee.gender }} </a>
                            <a><i class="flaticon2-phone"></i>{{ employee.phone_number }}</a>
                        </div>
                        <div class="kt-widget__info">
                            <div class="kt-widget__desc">
                                Address: {{ employee.address  }}
                            </div>
                            <div class="kt-widget__progress">
                                <div class="kt-widget__text">
                                    Progress
                                </div>
                                {% if not task_tuple.0 == 0 %}
                                <div class="progress" style="height: 5px;width: 100%;">
                                    <div class="progress-bar kt-bg-success" role="progressbar"
                                        style="width: {{ task_tuple.2 }}%;" aria-valuenow="{{ task_tuple.2 }}"
                                        aria-valuemin="0" aria-valuemax="{{ task_tuple.0 }}"></div>
                                </div>
                                <div class="kt-widget__stats">
                                    {{ task_tuple.2 }}%
                                </div>
                                {% else %}
                                <span>No tasks are assigned to this employee yet!</span>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="kt-widget__bottom" style="margin-left: 2% !important;">
                    <div class="kt-widget__item">
                        <div class="kt-widget__icon">
                            <i class="flaticon-list"></i>
                        </div>
                        <div class="kt-widget__details">
                            <span class="kt-widget__title">{{ task_tuple.0 }} Tasks Assigned</span>
                        </div>
                    </div>
                    <div class="kt-widget__item">
                        <div class="kt-widget__icon">
                            <i class="flaticon-clock-2"></i>
                        </div>
                        <div class="kt-widget__details">
                            <span class="kt-widget__title">{{ task_tuple.1 }} Tasks Pending</span>
                        </div>
                    </div>
                    <div class="kt-widget__item">
                        <div class="kt-widget__icon">
                            <i class="flaticon2-check-mark"></i>
                        </div>
                        <div class="kt-widget__details">
                            <span class="kt-widget__title">{{ task_tuple.3 }} Tasks Completed</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--end:: Portlet-->
</div>
{% endfor %}
<!-- end:: Content -->
{% endblock %}

{% block page-scripts %}
<script>
    function delOnClick(ref) {
        var url = "{% url 'employee:employee_delete' %}"
        var id = $(ref).attr("id")
        var intId = parseInt(id)
        var data = { id: intId, csrfmiddlewaretoken: '{{ csrf_token }}', contentType: 'application/json' }
        $.post(url, data, function (data, status) {
            location.reload(true)
        })
    }
</script>
{% endblock %}