product/urls.py
"""urls for product application."""

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from product.views.product_images_views import product_images_add_view, product_images_update_view
from product.views.product_views import (
    product_add_view,
    product_delete_view,
    product_detail_view,
    product_list_view,
    product_update_view
)

app_name = 'product'

urlpatterns = [
    path('products/', product_list_view, name='products'),
    path('product/<int:id>/', product_detail_view, name='product_detail'),
    path('product/add/', product_add_view, name='product_add'),
    path('product/update/<int:id>/', product_update_view, name='product_update'),
    path('product/delete/', product_delete_view, name='product_delete'),

    path('product_images/add/<int:product_id>/', product_images_add_view, name='product_images_add'),
    path('product_images/update/<int:product_id>/', product_images_update_view, name='product_images_update'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tms/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('tailor_management_system.urls')),
    path('', include('client.urls')),
    path('', include('order.urls')),
    path('', include('employee.urls')),
    path('', include('product.urls')),
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
    path('', include('notifications.urls')),
    path('help/', include('help.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # Provides login, logout, etc.
]

product/models.py
"""Models for product appliction."""

import os

from django.db import models
from django.dispatch import receiver
from django.forms.models import model_to_dict


class Product(models.Model):
    """Product model."""

    title = models.CharField(max_length=30, unique=True)
    product_type = models.CharField(max_length=30)
    price = models.PositiveSmallIntegerField()
    date_added = models.DateField(auto_now_add=True)
    stock = models.PositiveSmallIntegerField()
    description = models.TextField(blank=True, null=True)

    objects = models.Manager()

    def __str__(self):
        """Convert product object to string."""
        return 'Title:{} - Price:{} - Stock:{}'.format(
            self.title,
            self.price,
            self.stock
        )


class ProductImages(models.Model):
    """Product image model."""

    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    image1 = models.ImageField(max_length=500, upload_to='images/')
    image2 = models.ImageField(null=True, blank=True, max_length=500, upload_to='images/')
    image3 = models.ImageField(null=True, blank=True, max_length=500, upload_to='images/')
    image4 = models.ImageField(null=True, blank=True, max_length=500, upload_to='images/')
    image5 = models.ImageField(null=True, blank=True, max_length=500, upload_to='images/')

    objects = models.Manager()


@receiver(models.signals.post_delete, sender=ProductImages)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Delete file from filesystem when corresponding `ProductImages` object is deleted."""
    model_dict = model_to_dict(instance)
    model_dict.pop('id')
    model_dict.pop('product')
    for k, v in model_dict.items():
        if v:
            if os.path.isfile(v.path):
                os.remove(v.path)


@receiver(models.signals.pre_save, sender=ProductImages)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """Delete old file from filesystem when corresponding `ProductImages` object is updated with new file."""
    if not instance.id:
        return False

    try:
        old_instance = ProductImages.objects.get(id=instance.id)
    except ProductImages.DoesNotExist:
        return False

    old_instance_dict = model_to_dict(old_instance)
    old_instance_dict.pop('id')
    old_instance_dict.pop('product')
    new_instance_dict = model_to_dict(instance)
    for k, v in old_instance_dict.items():
        if v:
            if not v == new_instance_dict.get(k):
                if os.path.isfile(v.path):
                    os.remove(v.path)

product/forms.py
"""Forms for order application."""

import re

from django import forms
from django.core.exceptions import ValidationError

from product.models import Product, ProductImages


class ProductForm(forms.ModelForm):
    """Product model mapped form."""

    title = forms.CharField(max_length=30, min_length=4)
    product_type = forms.CharField(max_length=30, min_length=4)
    description = forms.CharField(widget=forms.Textarea, min_length=10)

    class Meta:
        """Specify fields to include."""

        model = Product
        fields = '__all__'

    def clean_title(self):
        """Check if title is valid."""
        title = self.cleaned_data['title']

        if not self._validate_text(title):
            raise ValidationError(('Invalid title.'))

        return title

    def clean_product_type(self):
        """Check if type is valid."""
        product_type = self.cleaned_data['product_type']

        if not self._validate_text(product_type):
            raise ValidationError(('Invalid product_type.'))

        return product_type

    def _validate_text(self, text):
        """Match valid text regex with text field."""
        return bool(re.match(
            r'^[_A-z0-9]*((-|\s)*[_A-z0-9])*$',
            str(text)
        ))


class ProductImagesForm(forms.ModelForm):
    """Product image model mapped form."""

    class Meta:
        """Meta for PI."""

        model = ProductImages
        exclude = ('product',)

product/views/product_images_views.py
"""Product related views."""

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from rest_framework.views import View

from product.forms import ProductImagesForm
from product.models import Product, ProductImages


class ProductImagesAddView(LoginRequiredMixin, View):
    """Class based view for adding new product images."""

    def get(self, request, product_id):
        """Return add new product image form."""
        product = get_object_or_404(Product, id=product_id)
        form = ProductImagesForm()
        return render(request, 'product_images/add-product_images.html',
                      {'form': form, 'func': 'Add', 'product': product})

    def post(self, request, product_id):
        """Save product image and redirect to product list."""
        product = get_object_or_404(Product, id=product_id)
        form = ProductImagesForm(request.POST, request.FILES)
        if form.is_valid():
            new_product_images = form.save(commit=False)
            new_product_images.product = product
            new_product_images.save()
            return redirect('product:product_detail', id=product_id)
        else:
            return render(
                request,
                'product_images/add-product_images.html',
                {'form': form, 'func': 'Add', 'product': product}
            )


product_images_add_view = ProductImagesAddView.as_view()


class ProductImagesUpdateView(LoginRequiredMixin, View):
    """Class based view for updating product images."""

    def get(self, request, product_id):
        """Return update product images form."""
        product = get_object_or_404(Product, id=product_id)
        product_images = get_object_or_404(ProductImages, product=product)
        form = ProductImagesForm(instance=product_images)
        return render(request, 'product_images/add-product_images.html',
                      {'form': form, 'func': 'Update', 'product': product})

    def post(self, request, product_id):
        """Save product and redirect to product list."""
        product = get_object_or_404(Product, id=product_id)
        product_images = get_object_or_404(ProductImages, product=product)
        form = ProductImagesForm(request.POST, request.FILES, instance=product_images)
        if form.is_valid():
            new_product_images = form.save(commit=False)
            new_product_images.product = product
            new_product_images.save()
            return redirect('product:product_detail', id=product_id)
        else:
            return render(
                request,
                'product_images/add-product_images.html',
                {'form': form, 'func': 'Update',  'product': product}
            )


product_images_update_view = ProductImagesUpdateView.as_view()

product/views/product_views.py
"""Product related views."""

from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms.models import model_to_dict
from django.shortcuts import get_object_or_404, redirect, render
from rest_framework.views import View

from product.forms import ProductForm
from product.models import Product, ProductImages


class ProductListView(LoginRequiredMixin, View):
    """List products view."""

    def get(self, request):
        """Render product list template.."""
        products = Product.objects.all()
        context = {
            'products': products,
        }
        return render(request, 'product/list-products.html', context)
product_list_view = ProductListView.as_view()


class ProductDetailView(LoginRequiredMixin, View):
    """Get product view."""

    def get(self, request, id):
        """Render product detail template.."""
        product = get_object_or_404(Product, id=id)
        product_images = ProductImages.objects.filter(product=product).first()
        if product_images:
            product_images_dict = model_to_dict(product_images)
            product_images_dict.pop('id')
            product_images_dict.pop('product')
        else:
            product_images_dict = {}
        context = {
            'product': product,
            'product_images': product_images,
            'product_images_dict': product_images_dict
        }
        return render(request, 'product/product-detail.html', context)
product_detail_view = ProductDetailView.as_view()


class ProductDeleteView(LoginRequiredMixin, View):
    """Delete product view."""

    def post(self, request):
        """Delete product."""
        id = request.POST.get('id')
        get_object_or_404(Product, id=id).delete()
        return redirect('product:products')
product_delete_view = ProductDeleteView.as_view()


class ProductAddView(LoginRequiredMixin, View):
    """Class based view for adding new product."""

    def get(self, request):
        """Return add new product form."""
        form = ProductForm()
        return render(request, 'product/add-product.html',
                      {'form': form, 'func': 'Add'})

    def post(self, request):
        """Save product and redirect to product list."""
        form = ProductForm(request.POST)
        if form.is_valid():
            new_product = form.save()
            return redirect('product:product_images_add', product_id=new_product.id)
        else:
            return render(request, 'product/add-product.html', {'form': form, 'func': 'Add'})
product_add_view = ProductAddView.as_view()


class ProductUpdateView(LoginRequiredMixin, View):
    """Class based view for Updating new product."""

    def get(self, request, id):
        """Return Update new product form."""
        product = get_object_or_404(Product, id=id)
        form = ProductForm(instance=product)
        return render(request, 'product/add-product.html',
                      {'form': form, 'func': 'Update', 'product': product})

    def post(self, request, id):
        """Update product and redirect to product list."""
        product = get_object_or_404(Product, id=id)
        form = ProductForm(request.POST, instance=product)
        has_images = ProductImages.objects.filter(product=product).exists()
        if form.is_valid():
            new_product = form.save()
            if has_images:
                return redirect('product:product_images_update', product_id=new_product.id)
            else:
                return redirect('product:product_images_add', product_id=new_product.id)
        else:
            return render(request, 'product/add-product.html', {'form': form, 'func': 'Update', 'product': product})
product_update_view = ProductUpdateView.as_view()

product/templates/product_images/add-product_images.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<!-- begin:: Content -->

<div class="kt-container  kt-grid__item kt-grid__item--fluid">
    <div class="kt-portlet">
        <div class="kt-portlet__body kt-portlet__body--fit">
            <div class="kt-grid  kt-wizard-v2 kt-wizard-v2--white" id="kt_wizard_v2" data-ktwizard-state="step-first">
                <div class="kt-grid__item kt-wizard-v2__aside">

                    <!--begin: Form Wizard Nav -->
                    <div class="kt-wizard-v2__nav">
                        <div class="kt-wizard-v2__nav-items kt-wizard-v2__nav-items--clickable">

                            <!--doc: Replace A tag with SPAN tag to disable the step link click -->
                            <div class="kt-wizard-v2__nav-item" data-ktwizard-type="step">
                                <div class="kt-wizard-v2__nav-body">
                                    <div class="kt-wizard-v2__nav-icon">
                                        <i class="flaticon-plus"></i>
                                    </div>
                                    <div class="kt-wizard-v2__nav-label">
                                        <div class="kt-wizard-v2__nav-label-title">
                                            Product Information
                                        </div>
                                        <div class="kt-wizard-v2__nav-label-desc">
                                            Add Product Details
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="kt-wizard-v2__nav-item" data-ktwizard-type="step" data-ktwizard-state="current">
                                <div class="kt-wizard-v2__nav-body">
                                    <div class="kt-wizard-v2__nav-icon">
                                        <i class="flaticon2-image-file"></i>
                                    </div>
                                    <div class="kt-wizard-v2__nav-label">
                                        <div class="kt-wizard-v2__nav-label-title">
                                            Product Images
                                        </div>
                                        <div class="kt-wizard-v2__nav-label-desc">
                                            Add images for your product.
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!--end: Form Wizard Nav -->
                </div>
                <div class="kt-grid__item kt-grid__item--fluid kt-wizard-v2__wrapper">

                    <!--begin: Form Wizard Form-->
                    <form class="kt-form"
                        {% if func == "Add" %}action="{% url 'product:product_images_add' product.id %}"
                        {% else %}action="{% url 'product:product_images_update' product.id %}" {% endif %}
                        method="post" enctype="multipart/form-data">
                        <!--begin: Form Wizard Step 1-->
                        <div class="kt-wizard-v2__content" data-ktwizard-type="step-content"
                            data-ktwizard-state="current"
                            style="padding-bottom:0em !important; margin-bottom:0em !important; border-bottom:0px !important;">
                            <div class="kt-heading kt-heading--md">Enter Product Details</div>
                            <div class="kt-form__section kt-form__section--first">
                                <div class="kt-wizard-v2__form">
                                    {% csrf_token %}
                                    <div id="div_id_image1" class="form-group"> <label for="id_image1"
                                            class=" requiredField">
                                            Image1<span class="asteriskField">*</span> </label>
                                        <div class="custom-file ">
                                            <input type="file" name="image1" accept="image/*"
                                                class="clearablefileinput form-control custom-file-input"
                                                id="id_image1"> <label class="custom-file-label" for="id_image1">Choose
                                                file</label> </div>
                                    </div>
                                    <div id="div_id_image2" class="form-group"> <label for="id_image2" class="">
                                            Image2
                                        </label>
                                        <div class="custom-file ">
                                            <input type="file" name="image2" accept="image/*"
                                                class="clearablefileinput form-control custom-file-input"
                                                id="id_image2"> <label class="custom-file-label" for="id_image2">Choose
                                                file</label> </div>
                                    </div>
                                    <div id="div_id_image3" class="form-group"> <label for="id_image3" class="">
                                            Image3
                                        </label>
                                        <div class="custom-file ">
                                            <input type="file" name="image3" accept="image/*"
                                                class="clearablefileinput form-control custom-file-input"
                                                id="id_image3"> <label class="custom-file-label" for="id_image3">Choose
                                                file</label> </div>
                                    </div>
                                    <div id="div_id_image4" class="form-group"> <label for="id_image4" class="">
                                            Image4
                                        </label>
                                        <div class="custom-file "> <input type="file" name="image4" accept="image/*"
                                                class="clearablefileinput form-control custom-file-input"
                                                id="id_image4"> <label class="custom-file-label" for="id_image4">Choose
                                                file</label> </div>
                                    </div>
                                    <div id="div_id_image5" class="form-group"> <label for="id_image5" class="">
                                            Image5
                                        </label>
                                        <div class="custom-file "> <input type="file" name="image5" accept="image/*"
                                                class="clearablefileinput form-control custom-file-input"
                                                id="id_image5"> <label class="custom-file-label" for="id_image5">Choose
                                                file</label> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--end: Form Wizard Step 1-->

                        <!--begin: Form Actions -->

                        <div class="kt-form__actions float-right">
                            <a href="{% url 'product:products' %}" class="btn btn-default">Skip</a>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>

                        <!--end: Form Actions -->
                    </form>

                    <!--end: Form Wizard Form-->
                </div>
            </div>
        </div>
    </div>
</div>

<!-- end:: Content -->
{% endblock %}