client/urls.py
"""urls for client application."""

from django.urls import path

from client.client_apis import client_detail_view_api, client_view
from client.views.client_views import (
    client_add_view,
    client_delete_view,
    client_detail_view,
    client_list_view,
    client_update_view
)
from client.views.measurement_views import measurements_add_view, measurements_update_view
from .views.client_views import client_dashboard
app_name = 'client'

urlpatterns = [
    path('clients/', client_list_view, name='clients'),
    path('clients/detail/<int:pk>/', client_detail_view, name='client_detail'),
    path('clients/delete/', client_delete_view, name='client_delete'),
    path('clients/add/', client_add_view, name='client_add'),
    path('clients/update/<int:pk>/', client_update_view, name='client_update'),
    path('clients/measurements/add/<int:client_id>/', measurements_add_view, name='measurment_add'),
    path('clients/measurements/update/<int:client_id>/', measurements_update_view, name='measurment_update'),
    path('dashboard/', client_dashboard, name='client_dashboard'),
    # path('create-client/', ClientCreateView.as_view(), name='create_client'),
    # API END POINTS
    path('clients/api/', client_view, name='clients_api'),
    path('clients/api/detail/<int:pk>/', client_detail_view_api, name='client_detail_api'),
    path('clients/api/delete/<int:pk>/', client_detail_view_api, name='client_delete_api'),
    path('clients/api/add/', client_view, name='client_add_api'),
    path('clients/api/update/<int:pk>/', client_detail_view_api, name='client_update_api'),
]

employee/urls.py
"""urls for employee application."""

from django.urls import path

from employee.views import (
    employee_add_view,
    employee_delete_view,
    employee_detail_view,
    employee_list_view,
    employee_update_view
)

app_name = 'employee'

urlpatterns = [
    path('employees/', employee_list_view, name='employees'),
    path('employee/<int:id>/', employee_detail_view, name='employee_detail'),
    path('employee/add/', employee_add_view, name='employee_add'),
    path('employee/update/<int:id>/', employee_update_view, name='employee_update'),
    path('employee/delete/', employee_delete_view, name='employee_delete'),
]

order/urls.py
"""urls for order application."""

from django.urls import path

from order.views.order_views import order_add_view, order_detail_view, order_list_view, order_update_view,orders_with_pending_payments,header_top_view
from order.views.task_views import task_add_view, task_delete_view, task_detail_view, task_list_view, task_update_view

app_name = 'order'

urlpatterns = [
    path('orders/', order_list_view, name='orders'),
    path('order/<int:id>/', order_detail_view, name='order_detail'),
    path('order/add/<int:client_id>/', order_add_view, name='order_add'),
    path('order/update/<int:id>/', order_update_view, name='order_update'),
    path('orders/pending/', orders_with_pending_payments, name='pending_orders'),
    path('header/', header_top_view, name='header_top'),
    # TASK URLS
    path('tasks/', task_list_view, name='tasks'),
    path('task/<int:id>/', task_detail_view, name='task_detail'),
    path('task/add/<int:order_id>/', task_add_view, name='task_add'),
    path('task/update/<int:id>/', task_update_view, name='task_update'),
    path('task/delete/', task_delete_view, name='task_delete'),
]

tms/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('tailor_management_system.urls')),
    path('', include('client.urls')),
    path('', include('order.urls')),
    path('', include('employee.urls')),
    path('', include('product.urls')),
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
    path('', include('notifications.urls')),
    path('help/', include('help.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # Provides login, logout, etc.
]

order/models.py
"""Models for order application."""

from django.db import models

from client.models import Client
from employee.models import Employee
from product.models import Product


class Order(models.Model):
    """Order model."""

    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, blank=True, default=None, null=True, on_delete=models.CASCADE)

    RECIEVED, IN_PROGRESS, DELIVERED, CLOSED = 'R', 'I', 'D', 'C'
    ORDER_STATUS_CHOICES = [(RECIEVED, 'Recieved'), (IN_PROGRESS, 'In Progress'),
                            (DELIVERED, 'Delivered'), (CLOSED, 'Closed')]

    status = models.CharField(
        max_length=1,
        choices=ORDER_STATUS_CHOICES,
        default=RECIEVED
    )
    payment_status = models.BooleanField(default=False)
    payment_amount = models.PositiveSmallIntegerField()
    advance_payment_amount = models.PositiveSmallIntegerField(default=0, blank=True)
    delivery_date = models.DateField(blank=True, null=True)
    date_recieved = models.DateField(auto_now_add=True)
    order = models.CharField(max_length=50)
    instructions = models.TextField(max_length=500, blank=True, null=True)

    objects = models.Manager()

    def __str__(self):
        """Convert object to String."""
        return 'Id:{} - DeliveryDate:{} - ClientName:{}'.format(
            self.id,
            self.delivery_date,
            self.client.name
        )
    def is_payment_pending(self):
        return not self.payment_status

class Task(models.Model):
    """Task Model."""

    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, null=True, blank=True, on_delete=models.SET_NULL)
    description = models.TextField(max_length=500)

    CREATED, IN_PROGRESS, COMPLETED = 'CR', 'I', 'C'
    TASK_STATUS_CHOICES = [(CREATED, 'Created'), (IN_PROGRESS, 'In Progress'), (COMPLETED, 'Completed')]

    status = models.CharField(max_length=2, choices=TASK_STATUS_CHOICES, default=CREATED)
    deadline = models.DateField()
    objects = models.Manager()

    def __str__(self):
        """Convert object to String."""
        return 'OrderId:{} - EmployeeName:{} - Deadline:{} - Task:{}'.format(
            self.order_id.id,
            self.employee_id.name,
            self.deadline,
            self.description
        )

order/forms.py
"""Forms for order application."""

import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.forms.widgets import SelectDateWidget

from order.models import Order, Task


class OrderForm(forms.ModelForm):
    """Order model mapped form."""

    order = forms.CharField(max_length=50, min_length=5)
    instructions = forms.CharField(widget=forms.Textarea, max_length=500, min_length=10)
    delivery_date = forms.DateField(widget=SelectDateWidget(empty_label="Delivery Date"))

    class Meta:
        """Specify fields to include."""

        model = Order
        exclude = ('date_recieved', 'client')

    def clean_delivery_date(self):
        """Check if date is valid."""
        delivery_date = self.cleaned_data['delivery_date']
        if delivery_date < datetime.date.today():
            raise ValidationError(('Delivery date can not be in past.'))

        return delivery_date

    def clean_status(self):
        """Check if status is valid."""
        status = self.cleaned_data['status']

        if (status == Order.DELIVERED) or (status == Order.CLOSED):
            incomplete_task_count = Task.objects.exclude(status=Task.COMPLETED).count()
            if incomplete_task_count:
                raise ValidationError(('Some tasks against this order are still pending, please finish them first.'))

        return status


class TaskForm(forms.ModelForm):
    """Task model mapped form."""

    description = forms.CharField(widget=forms.Textarea, max_length=500, min_length=10)
    deadline = forms.DateField(widget=SelectDateWidget(empty_label="Deadline"))

    class Meta:
        """Specify fields to include."""

        model = Task
        exclude = ('order',)

    def clean_deadline(self):
        """Check if date is valid."""
        deadline = self.cleaned_data['deadline']

        if deadline < datetime.date.today():
            raise ValidationError(('Deadline can not be in past.'))

        return deadline

order/views/order_views.py
"""Views for order application."""

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from rest_framework.views import View

from client.models import Client
from order.forms import OrderForm
from order.models import Order, Task

def header_top_view(request):
    pending_orders = Order.objects.filter(payment_status=False)
    pending_count = pending_orders.count()
    # Include any other data you need for the header
    return render(request, 'header/header-topbar.html', {'pending_count': pending_count})

def orders_with_pending_payments(request):
    pending_orders = Order.objects.filter(payment_status=False)
    pending_count = pending_orders.count()
    return render(request, 'order/pending_orders.html', {'pending_orders': pending_orders, 'pending_count': pending_count})



class OrderListView(LoginRequiredMixin, View):
    """Class based view for Order for listing all the orders."""

    def get(self, request):
        """Render order list template.."""
        orders = Order.objects.exclude(status=Order.CLOSED)
        context = {
            'orders': orders,
        }
        return render(request, 'order/list-orders.html', context)


order_list_view = OrderListView.as_view()


class OrderDetailView(LoginRequiredMixin, View):
    """Class based view for Order for detail of order."""

    def get(self, request, id):
        """Render order detail tempalte.."""
        order = Order.objects.get(id=id)
        tasks = Task.objects.filter(order=order)
        context = {
            'order': order,
            'tasks': tasks
        }
        return render(request, 'order/order-detail.html', context)


order_detail_view = OrderDetailView.as_view()


class OrderAddView(LoginRequiredMixin, View):
    """Class based view for adding new order."""

    def get(self, request, client_id):
        """Return add new order form."""
        client = get_object_or_404(Client, id=client_id)
        form = OrderForm()
        return render(request, 'order/add-order.html',
                      {'form': form, 'func': 'Add', 'client': client})

    def post(self, request, client_id):
        """Save order and redirect to order list."""
        form = OrderForm(request.POST)
        client = get_object_or_404(Client, id=client_id)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.client = client
            new_order.save()
            return redirect('order:orders')
        else:
            return render(request, 'order/add-order.html', {'form': form, 'func': 'Add', 'client': client})


order_add_view = OrderAddView.as_view()


class OrderUpdateView(LoginRequiredMixin, View):
    """Class based view for updating new order."""

    def get(self, request, id):
        """Return add new order form."""
        order = get_object_or_404(Order, id=id)
        form = OrderForm(instance=order)
        return render(request, 'order/add-order.html',
                      {'form': form, 'func': 'Update', 'order': order})

    def post(self, request, id):
        """Save order and redirect to order list."""
        order = get_object_or_404(Order, id=id)
        client = get_object_or_404(Client, id=order.client.id)
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.client = client
            new_order.save()
            return redirect('order:orders')
        else:
            return render(request, 'order/add-order.html', {'form': form, 'func': 'Update', 'order': order})


order_update_view = OrderUpdateView.as_view()

order/views/task_views.py
"""Views for order application."""

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from rest_framework.views import View

from order.forms import TaskForm
from order.models import Order, Task


class TaskListView(LoginRequiredMixin, View):
    """Class based view for Order for listing all the orders."""

    def get(self, request):
        """Render task list template.."""
        tasks = Task.objects.all()
        context = {
            'tasks': tasks,
        }
        return render(request, 'task/list-tasks.html', context)


task_list_view = TaskListView.as_view()


class TaskDetailView(LoginRequiredMixin, View):
    """Class based view for tasks for detail of tasks."""

    def get(self, request, id):
        """Render tasks detail tempalte.."""
        task = Task.objects.get(id=id)
        context = {
            'task': task,
        }
        return render(request, 'task/task-detail.html', context)


task_detail_view = TaskDetailView.as_view()


class TaskAddView(LoginRequiredMixin, View):
    """Class based view for adding new task."""

    def get(self, request, order_id):
        """Return add new task form."""
        order = get_object_or_404(Order, id=order_id)
        form = TaskForm()
        return render(request, 'task/add-task.html',
                      {'form': form, 'func': 'Add', 'order': order})

    def post(self, request, order_id):
        """Save task and redirect to task list."""
        form = TaskForm(request.POST)
        order = get_object_or_404(Order, id=order_id)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.order = order
            new_task.save()
            return redirect('order:tasks')
        else:
            return render(request, 'task/add-task.html', {'form': form, 'func': 'Add', 'order': order})


task_add_view = TaskAddView.as_view()


class TaskUpdateView(LoginRequiredMixin, View):
    """Class based view for updating new task."""

    def get(self, request, id):
        """Return add new task form."""
        task = get_object_or_404(Task, id=id)
        form = TaskForm(instance=task)
        return render(request, 'task/add-task.html',
                      {'form': form, 'func': 'Update', 'task': task})

    def post(self, request, id):
        """Save order and redirect to task list."""
        task = get_object_or_404(Task, id=id)
        order = get_object_or_404(Order, id=task.order.id)
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.order = order
            new_task.save()
            return redirect('order:tasks')
        else:
            return render(request, 'task/add-task.html', {'form': form, 'func': 'Update', 'task': task})


task_update_view = TaskUpdateView.as_view()


class TaskDeleteView(LoginRequiredMixin, View):
    """Class based view for tasks for deletion of task."""

    def post(self, request):
        """Render task list tempalte after deletion."""
        id = request.POST.get('id')
        task = get_object_or_404(Task, id=id)
        task.delete()
        return redirect('order:tasks')


task_delete_view = TaskDeleteView.as_view()

order/templates/order/add-order.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}
{% block content %}
<!-- begin:: Content -->
<div class="kt-container  kt-grid__item kt-grid__item--fluid">

    <!--begin::Portlet-->
    <div class="kt-portlet">
        <div class="kt-portlet__head">
            <div class="kt-portlet__head-label">
                <h3 class="kt-portlet__head-title">
                    Add Details
                </h3>
            </div>
        </div>

        <!--begin::Form-->
        {% if func == "Add" %}
        <form class="kt-form kt-portlet__body" action="{% url 'order:order_add' client.id %}" method="post">
        {% else %}
        <form class="kt-form kt-portlet__body" action="{% url 'order:order_update' order.id %}" method="post">
        {% endif %}    
            {% csrf_token %}
            {{ form|crispy }}
            <div class="kt-portlet__foot">
                <div class="kt-form__actions">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-secondary">Reset</button>
                </div>
            </div>
        </form>

        <!--end::Form-->
    </div>

    <!--end::Portlet-->
</div>

<!-- end:: Content -->
{% endblock %}

order/templates/order/add-task-button.html
<div class="kt-portlet__head kt-portlet__head--lg">
    <div class="kt-portlet__head-label">
        <span class="kt-portlet__head-icon">
        </span>
    </div>
    <div class="kt-portlet__head-toolbar">
        <div class="kt-portlet__head-wrapper">
            <div class="kt-portlet__head-actions">
                &nbsp;
                <a href="{% url 'order:task_add' order.id %}" class="btn btn-brand btn-elevate btn-icon-sm">
                    <i class="la la-plus"></i>
                    Add Task
                </a>
                &nbsp;
            </div>
        </div>
    </div>
</div>

order/templates/order/order-detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load get_status %}
{% load get_dict_value %}
{% load static %}

{% block content %}
<!-- begin:: Content -->
<div class="kt-container  kt-grid__item kt-grid__item--fluid">
    <div class="kt-portlet__head kt-portlet__head--lg text-right">
        <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
            </span>
        </div>
        <div class="kt-portlet__head-toolbar">
            <div class="kt-portlet__head-wrapper">
                <div class="kt-portlet__head-actions">
                    &nbsp;
                    <a href="{% url 'order:task_add' order.id %}" class="btn btn-brand btn-elevate btn-icon-sm">
                        <i class="la la-plus"></i>
                        Add Task
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!--Begin::App-->
    <div class="kt-grid kt-grid--desktop kt-grid--ver kt-grid--ver-desktop kt-app" style="padding-top: 1% !important;">

        <!--Begin:: App Aside Mobile Toggle-->
        <button class="kt-app__aside-close" id="kt_user_profile_aside_close">
            <i class="la la-close"></i>
        </button>

        <!--End:: App Aside Mobile Toggle-->

        <!--Begin:: App Aside-->
        <div class="kt-grid__item kt-app__toggle kt-app__aside" id="kt_user_profile_aside">

            <!--Begin::Portlet-->
            <div class="kt-portlet kt-portlet--height-fluid-">
                <div class="kt-portlet__head kt-portlet__head--noborder">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                        </h3>
                    </div>
                    <div class="kt-portlet__head-toolbar">
                        <a href="#" class="btn btn-clean btn-sm btn-icon btn-icon-md" data-toggle="dropdown">
                            <i class="flaticon-more-1"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <ul class="kt-nav">
                                <li class="kt-nav__item">
                                    <a href="{% url 'order:order_update' order.id %}" class="kt-nav__link">
                                        <i class="kt-nav__link-icon flaticon2-pen"></i>
                                        <span class="kt-nav__link-text">Edit</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="kt-portlet__body">

                    <!--begin::Widget -->
                    <div class="kt-widget kt-widget--user-profile-2">
                        <div class="kt-widget__head">
                            <div class="kt-widget__info" style="padding-left: 0em !important;">
                                <a class="kt-widget__username">
                                    Order#{{ order.id }}
                                </a>
                            </div>
                        </div>
                        </br>
                        <div class="kt-widget__body">
                            <div class="kt-widget__item">
                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">Order Client:</span>
                                    <a href="{% url 'client:client_detail' order.client.id %}"
                                        class="kt-widget__data">{{ order.client.username }}</a>
                                </div>
                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">Product:</span>
                                    <a
                                        class="kt-widget__data">{% if order.product %}{{ order.prodeuct.title }}{% else %}Custom{% endif %}</a>
                                </div>
                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">Status:</span>
                                    <a class="kt-widget__data">{% get_status "ORDER" order.status %}</a>
                                </div>
                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">Payment Status:</span>
                                    <a class="kt-widget__data">{{ order.payment_status }}</a>
                                </div>
                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">Payment Amount:</span>
                                    <span class="kt-widget__data">{{ order.payment_amount }}</span>
                                </div>

                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">Advance payment amount:</span>
                                    <span class="kt-widget__data">{{ order.advance_payment_amount }}</span>
                                </div>
                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">Delivery Date:</span>
                                    <span class="kt-widget__data">{{ order.delivery_date }}</span>
                                </div>
                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">Date Recieved:</span>
                                    <span class="kt-widget__data">{{ order.date_recieved }}</span>
                                </div>
                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">Order:</span>
                                    <span class="kt-widget__data">{{ order.order }}</span>
                                </div>
                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">Instructions:</span>
                                    <span class="kt-widget__data">{{ order.instructions }}</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!--end::Widget -->

                </div>
            </div>

            <!--End::Portlet-->

        </div>

        <!--End:: App Aside-->

        <!--Begin:: App Content-->
        <div class="kt-grid__item kt-grid__item--fluid kt-app__content">
            <div class="row">
                <div class="col-xl-12">

                    <!--begin:: Widgets/Finance Summary-->
                    <div class="kt-portlet kt-portlet--height-fluid">
                        <div class="kt-portlet__head">
                            <div class="kt-portlet__head-label">
                                <h3 class="kt-portlet__head-title">
                                    Tasks
                                </h3>
                            </div>
                        </div>
                        {% if tasks %}
                        {% for task in tasks %}
                        <div class="kt-portlet__body">
                            <div class="kt-widget12">
                                <div class="kt-portlet__head-toolbar" style="margin-left: 90% !important;">
                                    <a href="#" class="btn btn-label-brand btn-sm  btn-bold dropdown-toggle"
                                        data-toggle="dropdown">
                                        More
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-fit dropdown-menu-md">

                                        <!--begin::Nav-->
                                        <ul class="kt-nav">
                                            <li class="kt-nav__head">
                                                Task Options
                                            </li>
                                            <li class="kt-nav__separator"></li>
                                            <li class="kt-nav__item">
                                                <a href="{% url 'order:task_detail' task.id %}" class="kt-nav__link">
                                                    <i class="kt-nav__link-icon flaticon2-expand"></i>
                                                    <span class="kt-nav__link-text">Details</span>
                                                </a>
                                            </li>
                                            <li class="kt-nav__item">
                                                <a href="{% url 'order:task_update' task.id %}" class="kt-nav__link">
                                                    <i class="kt-nav__link-icon flaticon2-pen"></i>
                                                    <span class="kt-nav__link-text">Update</span>
                                                </a>
                                            </li>
                                        </ul>

                                        <!--end::Nav-->
                                    </div>
                                </div>
                                <div class="kt-widget12__content">
                                    <div class="kt-widget12__item">
                                        <div class="kt-widget12__info">
                                            <span class="kt-widget12__desc">Assigned To:</span>
                                            {% if task.employee %}
                                            <a href="{% url 'employee:employee_detail' task.employee.id %}"><span
                                                    class="kt-widget12__value">{{ task.employee.name }}</span></a>
                                            {% else %}
                                            <a><span class="kt-widget12__value">Unassigned</span></a>
                                            {% endif %}
                                        </div>
                                        <div class="kt-widget12__info">
                                            <span class="kt-widget12__desc">Task Status</span>
                                            <span class="kt-widget12__value">{% get_status "TASK" task.status %}</span>
                                        </div>
                                    </div>
                                    <div class="kt-widget12__item">
                                        <div class="kt-widget12__info">
                                            <span class="kt-widget12__desc">Task#</span>
                                            <a href="{% url 'order:task_detail' task.id %}"><span
                                                    class="kt-widget12__value">{{ task.id }}</span></a>
                                        </div>
                                        <div class="kt-widget12__info">
                                            <span class="kt-widget12__desc">Deadline</span>
                                            <span class="kt-widget12__value">{{ task.deadline }}</span>
                                        </div>
                                    </div>
                                    <div class="kt-widget12__item">
                                        <div class="kt-widget12__info">
                                            <span class="kt-widget12__desc">Description</span>
                                            <span class="kt-widget12__value">{{ task.description }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        {% else %}
                        <p class="h5 text-primary text-center" style="margin-right: 34% !important;">You haven't
                            created any tasks against this order yet. <a
                                href="{% url 'order:task_add' order.id %}">Create now?</a></p>
                        {% endif %}
                    </div>

                    <!--end:: Widgets/Finance Summary-->
                </div>
            </div>
        </div>


        <!--End:: App Content-->
    </div>
</div>
<!-- end:: Content -->
{% endblock %}

{% block page-scripts %}
<script src="{% static 'js/pages/crud/metronic-datatable/base/html-table.js' %}" type="text/javascript"></script>
{% endblock %}

order/templates/order/pending_orders.html
<!-- templates/pending_orders.html -->

{% extends 'base.html' %}
{% load static %}
{% load clean_title %}
{% load get_status %}

{% block content %}
    <div class="container mt-5">
        <h2>Pending Payments</h2>
        <div class="list-group">
            {% for order in pending_orders %}
                <a href="{% url 'order:order_detail' order.id %}" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">Order ID: {{ order.id }}</h5>
                        <small>{{ order.date_recieved|date:"F j, Y" }}</small>
                    </div>
                    <p class="mb-1">{{ order.client.name }}</p>
                    <small class="text-danger">Pending Payment: {{ order.payment_amount|floatformat:2 }}</small>
                </a>
            {% empty %}
                <div class="list-group-item">
                    <p class="mb-1">No pending payments.</p>
                </div>
            {% endfor %}
        </div>
    </div>
    {% endblock %}

    {% block page-scripts %}
    <script src="{% static 'js/pages/crud/metronic-datatable/base/html-table.js' %}" type="text/javascript"></script>
    {% endblock %}